try{
    throw new TypeError();

} catch(err){
    console.log(err)
    console.log("There was an error")
}

console.log("Our Program is Running")


